import { Inter } from 'next/font/google'
import './globals.css'
import SideBar from '../components/SideBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  const currentUser = null; //maybe implement cookies later on
  return (
    <html lang="en">
      <body className={`pl-16 ${inter.className}`}>
        <SideBar initialUser={currentUser} />
        {children}
      </body>
    </html>
  )
}
